FROM node:18-alpine
WORKDIR /app
COPY server/package.json server/tsconfig.json ./
COPY server/src ./src
RUN npm install --prefix ./ \
  && npm run build --prefix ./ || true
EXPOSE 5000
CMD ["npm", "run", "dev", "--prefix", "./"]
